import {
  Organization,
  User,
  Subscription,
  PlanLimits,
  Lead,
  Client,
  Property,
  Deal,
  SiteVisit,
  Task,
  FollowUpItem,
  WhatsAppConversation,
  WhatsAppTemplate,
  AutomationRule,
  DocumentRecord,
  NotificationItem,
  ActivityLogItem,
  SaaSAdminOverview,
  Invoice,
} from '@/types';

// ==========================================
// SAAS SUBSCRIPTION TIERS & LIMITS
// ==========================================

export const SAAS_PLANS: PlanLimits[] = [
  {
    tier: 'STARTER',
    name: 'Starter',
    priceMonthlyINR: 499,
    priceAnnualINR: 4790,
    maxUsers: 1,
    maxLeads: 100,
    maxProperties: 25,
    monthlyAIQuota: 100,
    hasWhatsAppCRM: false,
    hasAutomation: false,
    hasAdvancedReports: false,
    hasTeamManagement: false,
    hasPrioritySupport: false,
    features: [
      '1 User Seat',
      'Up to 100 Active Leads',
      'Up to 25 Listed Properties',
      'Basic CRM & Contact Management',
      'Standard Activity Reports',
      'Realty AI (100 Queries/mo)',
      'Email Support',
    ],
  },
  {
    tier: 'PROFESSIONAL',
    name: 'Professional',
    priceMonthlyINR: 1499,
    priceAnnualINR: 14390,
    maxUsers: 5,
    maxLeads: 1000,
    maxProperties: -1, // Unlimited
    monthlyAIQuota: 1000,
    hasWhatsAppCRM: true,
    hasAutomation: true,
    hasAdvancedReports: true,
    hasTeamManagement: true,
    hasPrioritySupport: false,
    features: [
      '5 User Seats',
      'Up to 1,000 Active Leads',
      'Unlimited Properties Inventory',
      'Interactive Deal Pipeline & Kanban',
      'Site Visit GPS Check-ins & Tracker',
      'Integrated WhatsApp CRM & Inbox',
      'Realty AI (1,000 Queries/mo)',
      'Advanced Sales & Revenue Reports',
      'Automated Lead Distribution',
      'WhatsApp Quick Templates',
    ],
  },
  {
    tier: 'BUSINESS',
    name: 'Business',
    priceMonthlyINR: 3999,
    priceAnnualINR: 38390,
    maxUsers: 15,
    maxLeads: -1, // Unlimited
    maxProperties: -1, // Unlimited
    monthlyAIQuota: 5000,
    hasWhatsAppCRM: true,
    hasAutomation: true,
    hasAdvancedReports: true,
    hasTeamManagement: true,
    hasPrioritySupport: true,
    features: [
      '15 User Seats (Expandable)',
      'Unlimited Leads & Contacts',
      'Unlimited Properties Inventory',
      'Multi-Stage Deal Pipeline Automation',
      'Full WhatsApp Business Automation Engine',
      'Advanced Realty AI Analytics & Drafting',
      'Custom Role-Based Access Control',
      'Exportable Executive PDF / CSV Reports',
      'Dedicated Account Manager',
      'Priority 24/7 SLA Support',
    ],
  },
];

// ==========================================
// ORGANIZATIONS & DEMO TENANTS
// ==========================================

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-apex-01',
    name: 'Velvet Apex Realty Pvt Ltd',
    slug: 'velvet-apex-realty',
    logoUrl: '/brand/velvet-code-logo.jpeg',
    phone: '+91 94436 47190',
    email: 'contact@apexrealty.in',
    address: 'Level 5, Capital Park Towers, Anna Salai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    businessType: 'AGENCY',
    website: 'https://apexrealty.in',
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'org-metro-02',
    name: 'Metroline Builders & Developers',
    slug: 'metroline-builders',
    phone: '+91 98450 12345',
    email: 'sales@metrolinebuilders.com',
    address: 'Indiranagar 100ft Road',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    businessType: 'BUILDER',
    website: 'https://metrolinebuilders.com',
    createdAt: '2026-02-15T11:30:00Z',
  },
  {
    id: 'org-skyline-03',
    name: 'Skyline Luxe Property Consultants',
    slug: 'skyline-luxe',
    phone: '+91 98201 67890',
    email: 'info@skylineluxe.in',
    address: 'Bandra Kurla Complex',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    businessType: 'BROKER',
    website: 'https://skylineluxe.in',
    createdAt: '2026-03-01T09:15:00Z',
  },
];

// ==========================================
// DEMO USERS
// ==========================================

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-01',
    name: 'Velvet Code',
    email: 'srilakshman73@gmail.com',
    phone: '+91 94436 47190',
    role: 'OWNER',
    organizationId: 'org-root-00',
    isSuperAdmin: true,
  },
  {
    id: 'usr-vikram-02',
    name: 'Velvet Code',
    email: 'owner@velvetcode.in',
    phone: '+91 94436 47190',
    role: 'OWNER',
    organizationId: 'org-apex-01',
  },
  {
    id: 'usr-ananya-03',
    name: 'Ananya Iyer',
    email: 'ananya@apexrealty.in',
    phone: '+91 98402 33445',
    role: 'ADMIN',
    organizationId: 'org-apex-01',
  },
  {
    id: 'usr-karthik-04',
    name: 'Karthik Subramanian',
    email: 'karthik@apexrealty.in',
    phone: '+91 98403 99887',
    role: 'MANAGER',
    organizationId: 'org-apex-01',
  },
  {
    id: 'usr-divya-05',
    name: 'Divya Krishnan',
    email: 'divya@apexrealty.in',
    phone: '+91 98404 11223',
    role: 'AGENT',
    organizationId: 'org-apex-01',
  },
];

// ==========================================
// INITIAL SUBSCRIPTION
// ==========================================

export const INITIAL_SUBSCRIPTION: Subscription = {
  id: 'sub-apex-01',
  organizationId: 'org-apex-01',
  tier: 'PROFESSIONAL',
  status: 'ACTIVE',
  priceMonthlyINR: 1499,
  billingCycle: 'monthly',
  currentPeriodStart: '2026-09-01T00:00:00Z',
  currentPeriodEnd: '2026-10-01T00:00:00Z',
  cancelAtPeriodEnd: false,
  razorpaySubscriptionId: 'sub_rzp_apex_998127',
  usage: {
    usersCount: 5,
    leadsCount: 248,
    propertiesCount: 12,
    aiRequestsUsed: 620,
  },
};

// ==========================================
// PROPERTIES DATASET (High Quality Indian Real Estate)
// ==========================================

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop-01',
    organizationId: 'org-apex-01',
    title: 'The Grand Emerald Heights - Luxury 3BHK',
    description:
      'Ultra-modern high-rise apartment on OMR with panoramic IT corridor skyline views, German modular kitchen, Italian marble flooring, and smart home automation.',
    propertyType: 'APARTMENT',
    status: 'AVAILABLE',
    priceINR: 14500000, // ₹1.45 Cr
    areaSqFt: 1850,
    bedrooms: 3,
    bathrooms: 3,
    furnishing: 'Fully Furnished',
    facing: 'North-East',
    address: 'Tower B, 14th Floor, Emerald Heights, OMR IT Expressway',
    locality: 'Perungudi / OMR',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600096',
    ownerName: 'V. Sundaram Properties',
    ownerPhone: '+91 98400 44332',
    amenities: [
      'Infinity Swimming Pool',
      'Clubhouse & Gym',
      '2 Covered Car Parks',
      '24/7 Power Backup',
      'EV Charging Station',
      'Landscaped Podium Garden',
    ],
    featuredImageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1000&q=80',
    ],
    assignedAgentId: 'usr-karthik-04',
    assignedAgentName: 'Karthik Subramanian',
    interestedLeadsCount: 14,
    siteVisitsCount: 6,
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-09-12T11:00:00Z',
  },
  {
    id: 'prop-02',
    organizationId: 'org-apex-01',
    title: 'Sobha Windsor Palm Villas - 4BHK Private Villa',
    description:
      'Regal English architecture villa with private heated swimming pool, manicured private lawn, double height living room, and servant quarters.',
    propertyType: 'VILLA',
    status: 'AVAILABLE',
    priceINR: 38500000, // ₹3.85 Cr
    areaSqFt: 3400,
    bedrooms: 4,
    bathrooms: 5,
    furnishing: 'Semi-Furnished',
    facing: 'East',
    address: 'Villa #18, Sobha Windsor Palm Enclave, Hope Farm Junction',
    locality: 'Whitefield',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560066',
    ownerName: 'Sobha Developers Group',
    ownerPhone: '+91 80 4422 1100',
    amenities: [
      'Private Swimming Pool',
      'Private Terrace Garden',
      'Home Theatre Room',
      'Gated Security & CCTV',
      'Solar Water Heating',
      '3 Car Parking Porch',
    ],
    featuredImageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1000&q=80',
    ],
    assignedAgentId: 'usr-ananya-03',
    assignedAgentName: 'Ananya Iyer',
    interestedLeadsCount: 9,
    siteVisitsCount: 4,
    createdAt: '2026-08-15T09:30:00Z',
    updatedAt: '2026-09-13T14:20:00Z',
  },
  {
    id: 'prop-03',
    organizationId: 'org-apex-01',
    title: 'Prestige Cyber View Residences - 2BHK Smart Home',
    description:
      'Compact luxury smart apartment 5 mins from Cyber Towers and major multinational tech campuses. High rental yield potential.',
    propertyType: 'APARTMENT',
    status: 'RESERVED',
    priceINR: 9200000, // ₹92 Lakhs
    areaSqFt: 1280,
    bedrooms: 2,
    bathrooms: 2,
    furnishing: 'Semi-Furnished',
    facing: 'North',
    address: 'Floor 8, Block A, Cyber View Towers, Mindspace Junction',
    locality: 'Hitec City',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500081',
    ownerName: 'K. Venkat Reddy',
    ownerPhone: '+91 99890 11223',
    amenities: [
      'Rooftop Sky Lounge',
      'Squash Court',
      'Co-working Pods',
      'Covered Parking',
      'Automated Access Control',
    ],
    featuredImageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80',
    ],
    assignedAgentId: 'usr-divya-05',
    assignedAgentName: 'Divya Krishnan',
    interestedLeadsCount: 18,
    siteVisitsCount: 8,
    createdAt: '2026-08-18T14:00:00Z',
    updatedAt: '2026-09-14T10:00:00Z',
  },
  {
    id: 'prop-04',
    organizationId: 'org-apex-01',
    title: 'Aura Waterfront Penthouse - 4BHK Sea Facing',
    description:
      'Unobstructed Bay of Bengal ocean view penthouse along the scenic East Coast Road. Private jacuzzi on sky deck, elevator opening into the foyer.',
    propertyType: 'PENTHOUSE',
    status: 'AVAILABLE',
    priceINR: 52000000, // ₹5.20 Cr
    areaSqFt: 4200,
    bedrooms: 4,
    bathrooms: 5,
    furnishing: 'Fully Furnished',
    facing: 'East',
    address: 'Sky Suite 1801, Aura Oceanside, ECR Beachside Road',
    locality: 'Palavakkam / ECR',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600041',
    ownerName: 'Rajeshwari Capital Holding',
    ownerPhone: '+91 98410 77889',
    amenities: [
      'Direct Private Beach Access',
      'Private Sky Deck & Jacuzzi',
      'Private Elevator Access',
      'Valet Concierge 24/7',
      'Wine Cellar & Cigar Lounge',
    ],
    featuredImageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80',
    ],
    assignedAgentId: 'usr-vikram-02',
    assignedAgentName: 'Velvet Code',
    interestedLeadsCount: 7,
    siteVisitsCount: 3,
    createdAt: '2026-08-20T12:00:00Z',
    updatedAt: '2026-09-11T16:00:00Z',
  },
  {
    id: 'prop-05',
    organizationId: 'org-apex-01',
    title: 'Godrej Green Meadows - 3BHK Eco Community',
    description:
      'IGBC Platinum certified green residential enclave with 80% open green landscapes, organic farming patch, and solar micro-grid.',
    propertyType: 'APARTMENT',
    status: 'AVAILABLE',
    priceINR: 11800000, // ₹1.18 Cr
    areaSqFt: 1620,
    bedrooms: 3,
    bathrooms: 3,
    furnishing: 'Semi-Furnished',
    facing: 'North',
    address: 'Block C, 5th Floor, Godrej Green Meadows, Sarjapur Main Road',
    locality: 'Sarjapur Road',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560035',
    ownerName: 'Godrej Properties Ltd',
    ownerPhone: '+91 80 6700 8900',
    amenities: [
      'Olympic Size Lap Pool',
      'Tennis & Badminton Courts',
      'Children Adventure Park',
      'Rainwater Harvesting Plant',
      '100% DG Power Backup',
    ],
    featuredImageUrl: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1000&q=80',
    ],
    assignedAgentId: 'usr-karthik-04',
    assignedAgentName: 'Karthik Subramanian',
    interestedLeadsCount: 16,
    siteVisitsCount: 5,
    createdAt: '2026-08-22T10:00:00Z',
    updatedAt: '2026-09-12T09:00:00Z',
  },
  {
    id: 'prop-06',
    organizationId: 'org-apex-01',
    title: 'Brigade Signature Commercial Suites - Grade A Office',
    description:
      'Premium corporate office floor with LEED Gold certification, column-free floor plate, central HVAC, and high-speed OTIS elevators.',
    propertyType: 'COMMERCIAL',
    status: 'AVAILABLE',
    priceINR: 68000000, // ₹6.80 Cr
    areaSqFt: 2600,
    furnishing: 'Fully Furnished',
    facing: 'East',
    address: 'Level 9, Brigade Signature Commercial Complex, BKC Main Avenue',
    locality: 'Bandra Kurla Complex',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400051',
    ownerName: 'Brigade Commercial Assets',
    ownerPhone: '+91 22 4000 8800',
    amenities: [
      'Central Chilled Water Aircon',
      'Multi-Level Basement Parking (8 slots)',
      'High-Speed Fibre Internet',
      'BMS Automated Safety Systems',
      'Executive Cafeteria & Lounge',
    ],
    featuredImageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1000&q=80',
    ],
    assignedAgentId: 'usr-vikram-02',
    assignedAgentName: 'Velvet Code',
    interestedLeadsCount: 5,
    siteVisitsCount: 2,
    createdAt: '2026-08-25T15:00:00Z',
    updatedAt: '2026-09-10T11:00:00Z',
  },
  {
    id: 'prop-07',
    organizationId: 'org-apex-01',
    title: 'Casagrand Elysium Township - 2.5BHK Gated Home',
    description:
      'Thoughtfully designed premium community with 40+ lifestyle amenities, near international schools and metro stations.',
    propertyType: 'APARTMENT',
    status: 'SOLD',
    priceINR: 8400000, // ₹84 Lakhs
    areaSqFt: 1190,
    bedrooms: 2,
    bathrooms: 2,
    furnishing: 'Unfurnished',
    facing: 'North',
    address: 'Flat 402, Block 3, Casagrand Elysium, Perungudi Tollgate',
    locality: 'Perungudi',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600096',
    ownerName: 'Casagrand Builder Pvt Ltd',
    ownerPhone: '+91 98400 11990',
    amenities: [
      'Swimming Pool with Kids Splash Pad',
      'Indoor Badminton Court',
      'Creche and Kids Play Arena',
      'Senior Citizen Relaxation Zone',
    ],
    featuredImageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80',
    ],
    assignedAgentId: 'usr-divya-05',
    assignedAgentName: 'Divya Krishnan',
    interestedLeadsCount: 12,
    siteVisitsCount: 7,
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-09-08T18:00:00Z',
  },
  {
    id: 'prop-08',
    organizationId: 'org-apex-01',
    title: 'Lodha Park Central Towers - 3BHK Sky Suite',
    description:
      'Ultra-exclusive 75-storey residential tower overlooking the 7-acre private park in South Mumbai.',
    propertyType: 'APARTMENT',
    status: 'AVAILABLE',
    priceINR: 49000000, // ₹4.90 Cr
    areaSqFt: 2100,
    bedrooms: 3,
    bathrooms: 4,
    furnishing: 'Semi-Furnished',
    facing: 'West',
    address: 'Wing C, Floor 42, Lodha Park Central, Pandurang Budhkar Marg',
    locality: 'Worli',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400018',
    ownerName: 'Lodha Luxury Assets',
    ownerPhone: '+91 22 6600 9900',
    amenities: [
      '7-Acre Private Urban Park',
      'Private Cinema & Screening Room',
      'Spa & Hydrotherapy Centre',
      'Helipad Access',
      'Full Concierge Support',
    ],
    featuredImageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80',
    ],
    assignedAgentId: 'usr-ananya-03',
    assignedAgentName: 'Ananya Iyer',
    interestedLeadsCount: 11,
    siteVisitsCount: 3,
    createdAt: '2026-08-28T11:00:00Z',
    updatedAt: '2026-09-13T12:00:00Z',
  },
  {
    id: 'prop-09',
    organizationId: 'org-apex-01',
    title: 'Adroit Altius Haven - 3BHK Duplex Penthouse',
    description:
      'Premier address in Coimbatore with sprawling balconies, high teakwood finishes, and tranquil race course greenery views.',
    propertyType: 'DUPLEX',
    status: 'AVAILABLE',
    priceINR: 16500000, // ₹1.65 Cr
    areaSqFt: 2350,
    bedrooms: 3,
    bathrooms: 4,
    furnishing: 'Fully Furnished',
    facing: 'East',
    address: 'Penthouse A, Altius Haven, Race Course Main Road',
    locality: 'Race Course',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    pincode: '641018',
    ownerName: 'Dr. G. Natarajan',
    ownerPhone: '+91 94433 88771',
    amenities: [
      'Covered Rooftop Garden',
      'Private Gym & Yoga Deck',
      '2 Covered Stilt Car Parks',
      '24/7 Security & Video Door Phone',
    ],
    featuredImageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1000&q=80',
    ],
    assignedAgentId: 'usr-karthik-04',
    assignedAgentName: 'Karthik Subramanian',
    interestedLeadsCount: 8,
    siteVisitsCount: 4,
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-14T08:00:00Z',
  },
  {
    id: 'prop-10',
    organizationId: 'org-apex-01',
    title: 'TVS Emerald Elements - 3BHK Lakeview Residence',
    description:
      'Serene lakefront apartments with private balcony overlooking freshwater lake, 10 mins from Chennai International Airport.',
    propertyType: 'APARTMENT',
    status: 'AVAILABLE',
    priceINR: 10500000, // ₹1.05 Cr
    areaSqFt: 1420,
    bedrooms: 3,
    bathrooms: 3,
    furnishing: 'Semi-Furnished',
    facing: 'North',
    address: 'Tower 4, 9th Floor, TVS Emerald Elements, 200 Feet Radial Road',
    locality: 'Kovilambakkam / Pallavaram',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600129',
    ownerName: 'TVS Emerald Living',
    ownerPhone: '+91 44 2830 5000',
    amenities: [
      'Lakefront Promenade',
      'Clubhouse with Badminton Court',
      'Rooftop Stargazing Deck',
      'EV Charging Bays',
    ],
    featuredImageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1000&q=80',
    ],
    assignedAgentId: 'usr-divya-05',
    assignedAgentName: 'Divya Krishnan',
    interestedLeadsCount: 15,
    siteVisitsCount: 6,
    createdAt: '2026-09-02T14:00:00Z',
    updatedAt: '2026-09-14T11:00:00Z',
  },
  {
    id: 'prop-11',
    organizationId: 'org-apex-01',
    title: 'Mahindra Eden Nature Enclave - 3BHK Forest View',
    description:
      'First biophilic residential community in South Bangalore with 85% wooded green cover and serene hill views.',
    propertyType: 'APARTMENT',
    status: 'AVAILABLE',
    priceINR: 13500000, // ₹1.35 Cr
    areaSqFt: 1780,
    bedrooms: 3,
    bathrooms: 3,
    furnishing: 'Unfurnished',
    facing: 'East',
    address: 'Wing B, Floor 11, Mahindra Eden, Kanakapura Road',
    locality: 'Kanakapura Road',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560062',
    ownerName: 'Mahindra Lifespaces',
    ownerPhone: '+91 80 6111 2222',
    amenities: [
      'Biophilic Forest Canopy Walkway',
      'Infinity Pool facing Reserve Forest',
      'Meditation Pavilion',
      'Solar Power Infrastructure',
    ],
    featuredImageUrl: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1000&q=80',
    ],
    assignedAgentId: 'usr-ananya-03',
    assignedAgentName: 'Ananya Iyer',
    interestedLeadsCount: 13,
    siteVisitsCount: 4,
    createdAt: '2026-09-05T09:00:00Z',
    updatedAt: '2026-09-13T15:00:00Z',
  },
  {
    id: 'prop-12',
    organizationId: 'org-apex-01',
    title: 'Purva Clermont Signature Flats - 2BHK Luxury',
    description:
      'Bespoke neoclassical residences crafted by Puravankara with easy access to Eastern Freeway and BKC.',
    propertyType: 'APARTMENT',
    status: 'AVAILABLE',
    priceINR: 21000000, // ₹2.10 Cr
    areaSqFt: 1050,
    bedrooms: 2,
    bathrooms: 2,
    furnishing: 'Semi-Furnished',
    facing: 'North-East',
    address: 'Tower 2, 16th Floor, Purva Clermont, Sion-Trombay Road',
    locality: 'Chembur',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400071',
    ownerName: 'Puravankara Projects Ltd',
    ownerPhone: '+91 22 2522 7700',
    amenities: [
      'Sky Lounge & Infinity Edge Pool',
      'Modern Gymnasium',
      'Podium Parking',
      '24/7 Security and Video Surveillance',
    ],
    featuredImageUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1000&q=80',
    ],
    assignedAgentId: 'usr-vikram-02',
    assignedAgentName: 'Velvet Code',
    interestedLeadsCount: 9,
    siteVisitsCount: 3,
    createdAt: '2026-09-07T12:00:00Z',
    updatedAt: '2026-09-14T09:30:00Z',
  },
];

// ==========================================
// LEADS DATASET (25 Realistic Leads)
// ==========================================

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-01',
    organizationId: 'org-apex-01',
    name: 'Rahul Sharma',
    phone: '+91 98401 22334',
    email: 'rahul.sharma@techcorp.com',
    source: 'WHATSAPP',
    status: 'NEGOTIATION',
    priority: 'HIGH',
    budgetMinINR: 13000000,
    budgetMaxINR: 16000000,
    preferredLocation: 'OMR, Chennai',
    preferredType: 'APARTMENT',
    interestedPropertyId: 'prop-01',
    interestedPropertyName: 'The Grand Emerald Heights - Luxury 3BHK',
    assignedToId: 'usr-karthik-04',
    assignedToName: 'Karthik Subramanian',
    nextFollowUpAt: '2026-09-14T15:30:00Z',
    score: 92,
    notes:
      'VP of Engineering at Amazon OMR. Highly interested in Tower B, 14th floor. Loan pre-approved with HDFC for ₹1.2 Cr. Negotiating on parking slot allotment.',
    createdAt: '2026-09-04T10:30:00Z',
    updatedAt: '2026-09-14T11:00:00Z',
  },
  {
    id: 'lead-02',
    organizationId: 'org-apex-01',
    name: 'Dr. Priya Raghavan',
    phone: '+91 94436 47190',
    email: 'priya.raghavan@apollohospitals.org',
    source: 'WEBSITE',
    status: 'SITE_VISIT',
    priority: 'URGENT',
    budgetMinINR: 35000000,
    budgetMaxINR: 42000000,
    preferredLocation: 'Whitefield, Bangalore',
    preferredType: 'VILLA',
    interestedPropertyId: 'prop-02',
    interestedPropertyName: 'Sobha Windsor Palm Villas - 4BHK Private Villa',
    assignedToId: 'usr-ananya-03',
    assignedToName: 'Ananya Iyer',
    nextFollowUpAt: '2026-09-15T11:00:00Z',
    score: 88,
    notes:
      'Senior Cardiologist relocating from London. Looking for immediate possession luxury villa with private lawn. Site visit scheduled for tomorrow morning.',
    createdAt: '2026-09-06T14:15:00Z',
    updatedAt: '2026-09-14T09:45:00Z',
  },
  {
    id: 'lead-03',
    organizationId: 'org-apex-01',
    name: 'Suresh Kumar & Meenakshi',
    phone: '+91 98840 99881',
    email: 'suresh.kumar@financials.co.in',
    source: 'REFERRAL',
    status: 'QUALIFIED',
    priority: 'HIGH',
    budgetMinINR: 8500000,
    budgetMaxINR: 10000000,
    preferredLocation: 'Hitec City, Hyderabad',
    preferredType: 'APARTMENT',
    interestedPropertyId: 'prop-03',
    interestedPropertyName: 'Prestige Cyber View Residences - 2BHK Smart Home',
    assignedToId: 'usr-divya-05',
    assignedToName: 'Divya Krishnan',
    nextFollowUpAt: '2026-09-14T16:00:00Z',
    score: 79,
    notes:
      'Referred by existing client. Looking for solid rental yield investment property in Hitec City. Sent video walkthrough.',
    createdAt: '2026-09-08T11:00:00Z',
    updatedAt: '2026-09-13T16:20:00Z',
  },
  {
    id: 'lead-04',
    organizationId: 'org-apex-01',
    name: 'Rajesh Varma (Varma Logistics)',
    phone: '+91 98200 44556',
    email: 'rajesh@varmalogistics.com',
    source: 'PHONE',
    status: 'WON',
    priority: 'HIGH',
    budgetMinINR: 50000000,
    budgetMaxINR: 55000000,
    preferredLocation: 'ECR, Chennai',
    preferredType: 'PENTHOUSE',
    interestedPropertyId: 'prop-04',
    interestedPropertyName: 'Aura Waterfront Penthouse - 4BHK Sea Facing',
    assignedToId: 'usr-vikram-02',
    assignedToName: 'Velvet Code',
    nextFollowUpAt: '2026-09-20T10:00:00Z',
    score: 98,
    notes:
      'Token advance of ₹25 Lakhs received. Sale agreement drafting in progress. Registration scheduled next week.',
    createdAt: '2026-08-25T16:00:00Z',
    updatedAt: '2026-09-13T17:30:00Z',
  },
  {
    id: 'lead-05',
    organizationId: 'org-apex-01',
    name: 'Aditya & Neha Deshmukh',
    phone: '+91 97654 32100',
    email: 'aditya.deshmukh@gmail.com',
    source: 'INSTAGRAM',
    status: 'CONTACTED',
    priority: 'MEDIUM',
    budgetMinINR: 11000000,
    budgetMaxINR: 13000000,
    preferredLocation: 'Sarjapur Road, Bangalore',
    preferredType: 'APARTMENT',
    interestedPropertyId: 'prop-05',
    interestedPropertyName: 'Godrej Green Meadows - 3BHK Eco Community',
    assignedToId: 'usr-karthik-04',
    assignedToName: 'Karthik Subramanian',
    nextFollowUpAt: '2026-09-14T17:30:00Z',
    score: 65,
    notes:
      'Saw Instagram reel of Godrej Green Meadows. Requested brochure and price breakdown with GST.',
    createdAt: '2026-09-10T12:45:00Z',
    updatedAt: '2026-09-14T08:15:00Z',
  },
  {
    id: 'lead-06',
    organizationId: 'org-apex-01',
    name: 'Kavitha Balasubramanian',
    phone: '+91 94440 88776',
    email: 'kavitha.b@yahoo.com',
    source: 'WALK_IN',
    status: 'NEW',
    priority: 'HIGH',
    budgetMinINR: 10000000,
    budgetMaxINR: 12000000,
    preferredLocation: 'Pallavaram / Kovilambakkam, Chennai',
    preferredType: 'APARTMENT',
    interestedPropertyId: 'prop-10',
    interestedPropertyName: 'TVS Emerald Elements - 3BHK Lakeview Residence',
    assignedToId: 'usr-divya-05',
    assignedToName: 'Divya Krishnan',
    nextFollowUpAt: '2026-09-14T14:30:00Z',
    score: 72,
    notes:
      'Walked into office after seeing lakefront billboard. Wants 3BHK east-facing unit on 8th or 9th floor.',
    createdAt: '2026-09-14T10:00:00Z',
    updatedAt: '2026-09-14T10:00:00Z',
  },
  {
    id: 'lead-07',
    organizationId: 'org-apex-01',
    name: 'Manish Chawla (FinTech Founder)',
    phone: '+91 98111 22334',
    email: 'manish@payzen.in',
    source: 'WEBSITE',
    status: 'SITE_VISIT',
    priority: 'HIGH',
    budgetMinINR: 45000000,
    budgetMaxINR: 52000000,
    preferredLocation: 'Worli, Mumbai',
    preferredType: 'APARTMENT',
    interestedPropertyId: 'prop-08',
    interestedPropertyName: 'Lodha Park Central Towers - 3BHK Sky Suite',
    assignedToId: 'usr-ananya-03',
    assignedToName: 'Ananya Iyer',
    nextFollowUpAt: '2026-09-16T15:00:00Z',
    score: 85,
    notes:
      'Looking for ultra-luxury high floor unit in South Mumbai with sea view and 3 car parks.',
    createdAt: '2026-09-07T14:20:00Z',
    updatedAt: '2026-09-13T11:40:00Z',
  },
  {
    id: 'lead-08',
    organizationId: 'org-apex-01',
    name: 'Senthil Nathan & Deepa',
    phone: '+91 98422 55667',
    email: 'senthilnathan@textiles.com',
    source: 'WHATSAPP',
    status: 'QUALIFIED',
    priority: 'MEDIUM',
    budgetMinINR: 15000000,
    budgetMaxINR: 18000000,
    preferredLocation: 'Race Course, Coimbatore',
    preferredType: 'DUPLEX',
    interestedPropertyId: 'prop-09',
    interestedPropertyName: 'Adroit Altius Haven - 3BHK Duplex Penthouse',
    assignedToId: 'usr-karthik-04',
    assignedToName: 'Karthik Subramanian',
    nextFollowUpAt: '2026-09-15T16:30:00Z',
    score: 75,
    notes:
      'Textile exporter from Tirupur seeking luxury residence in Coimbatore Race Course area.',
    createdAt: '2026-09-09T18:00:00Z',
    updatedAt: '2026-09-14T09:00:00Z',
  },
  {
    id: 'lead-09',
    organizationId: 'org-apex-01',
    name: 'Nikhil Agarwal',
    phone: '+91 99300 77665',
    email: 'nikhil.agarwal@capital.com',
    source: 'FACEBOOK',
    status: 'CONTACTED',
    priority: 'LOW',
    budgetMinINR: 20000000,
    budgetMaxINR: 23000000,
    preferredLocation: 'Chembur, Mumbai',
    preferredType: 'APARTMENT',
    interestedPropertyId: 'prop-12',
    interestedPropertyName: 'Purva Clermont Signature Flats - 2BHK Luxury',
    assignedToId: 'usr-divya-05',
    assignedToName: 'Divya Krishnan',
    nextFollowUpAt: '2026-09-17T11:30:00Z',
    score: 54,
    notes:
      'Inquired on Facebook Lead Ad. Currently comparing Chembur vs Ghatkopar options.',
    createdAt: '2026-09-11T16:30:00Z',
    updatedAt: '2026-09-13T10:15:00Z',
  },
  {
    id: 'lead-10',
    organizationId: 'org-apex-01',
    name: 'Dr. Anand Ramanathan',
    phone: '+91 98403 77112',
    email: 'anand.ramanathan@gmail.com',
    source: 'REFERRAL',
    status: 'NEGOTIATION',
    priority: 'URGENT',
    budgetMinINR: 13500000,
    budgetMaxINR: 15500000,
    preferredLocation: 'OMR, Chennai',
    preferredType: 'APARTMENT',
    interestedPropertyId: 'prop-01',
    interestedPropertyName: 'The Grand Emerald Heights - Luxury 3BHK',
    assignedToId: 'usr-karthik-04',
    assignedToName: 'Karthik Subramanian',
    nextFollowUpAt: '2026-09-14T18:00:00Z',
    score: 94,
    notes:
      'Ready to issue cheque today if price negotiated by 3%. Meeting at developer sales lounge at 6:00 PM.',
    createdAt: '2026-09-02T11:00:00Z',
    updatedAt: '2026-09-14T12:10:00Z',
  },
  {
    id: 'lead-11',
    organizationId: 'org-apex-01',
    name: 'Tanvi Shah',
    phone: '+91 98205 11994',
    email: 'tanvi.shah@mediahouse.com',
    source: 'WEBSITE',
    status: 'NEW',
    priority: 'MEDIUM',
    budgetMinINR: 18000000,
    budgetMaxINR: 22000000,
    preferredLocation: 'Mumbai Suburban',
    preferredType: 'APARTMENT',
    interestedPropertyId: 'prop-12',
    interestedPropertyName: 'Purva Clermont Signature Flats - 2BHK Luxury',
    assignedToId: 'usr-divya-05',
    assignedToName: 'Divya Krishnan',
    nextFollowUpAt: '2026-09-15T14:00:00Z',
    score: 58,
    notes: 'Submitted contact form from website hero section. Requested floor plan PDF.',
    createdAt: '2026-09-14T08:30:00Z',
    updatedAt: '2026-09-14T08:30:00Z',
  },
  {
    id: 'lead-12',
    organizationId: 'org-apex-01',
    name: 'Girish Chandra & Sons',
    phone: '+91 98455 66778',
    email: 'girish@chandragroup.in',
    source: 'PHONE',
    status: 'QUALIFIED',
    priority: 'HIGH',
    budgetMinINR: 60000000,
    budgetMaxINR: 75000000,
    preferredLocation: 'BKC, Mumbai',
    preferredType: 'COMMERCIAL',
    interestedPropertyId: 'prop-06',
    interestedPropertyName: 'Brigade Signature Commercial Suites - Grade A Office',
    assignedToId: 'usr-vikram-02',
    assignedToName: 'Velvet Code',
    nextFollowUpAt: '2026-09-16T11:00:00Z',
    score: 82,
    notes:
      'Looking for company regional headquarters in BKC. Requested commercial lease vs purchase analysis.',
    createdAt: '2026-09-05T14:00:00Z',
    updatedAt: '2026-09-12T17:00:00Z',
  },
  {
    id: 'lead-13',
    organizationId: 'org-apex-01',
    name: 'Aravind Swaminathan',
    phone: '+91 98841 33221',
    email: 'aravind.s@zoho.com',
    source: 'WHATSAPP',
    status: 'CONTACTED',
    priority: 'LOW',
    budgetMinINR: 9500000,
    budgetMaxINR: 11000000,
    preferredLocation: 'Kovilambakkam, Chennai',
    preferredType: 'APARTMENT',
    interestedPropertyId: 'prop-10',
    interestedPropertyName: 'TVS Emerald Elements - 3BHK Lakeview Residence',
    assignedToId: 'usr-divya-05',
    assignedToName: 'Divya Krishnan',
    nextFollowUpAt: '2026-09-15T18:00:00Z',
    score: 61,
    notes:
      'Zoho tech lead. Interested in 3BHK unit under ₹1.1 Cr with easy connectivity to GST road.',
    createdAt: '2026-09-12T15:10:00Z',
    updatedAt: '2026-09-14T09:20:00Z',
  },
  {
    id: 'lead-14',
    organizationId: 'org-apex-01',
    name: 'Rohan & Shweta Kulkarni',
    phone: '+91 98230 44112',
    email: 'rohan.k@consultancy.com',
    source: 'WEBSITE',
    status: 'SITE_VISIT',
    priority: 'MEDIUM',
    budgetMinINR: 12000000,
    budgetMaxINR: 14000000,
    preferredLocation: 'Kanakapura Road, Bangalore',
    preferredType: 'APARTMENT',
    interestedPropertyId: 'prop-11',
    interestedPropertyName: 'Mahindra Eden Nature Enclave - 3BHK Forest View',
    assignedToId: 'usr-ananya-03',
    assignedToName: 'Ananya Iyer',
    nextFollowUpAt: '2026-09-16T16:00:00Z',
    score: 77,
    notes:
      'Completed virtual tour. Physical site visit scheduled with family for Saturday morning.',
    createdAt: '2026-09-08T17:30:00Z',
    updatedAt: '2026-09-13T14:50:00Z',
  },
  {
    id: 'lead-15',
    organizationId: 'org-apex-01',
    name: 'Venkatesh Babu',
    phone: '+91 94441 55660',
    email: 'venkat.babu@autoancillary.com',
    source: 'OTHER',
    status: 'LOST',
    priority: 'LOW',
    budgetMinINR: 7500000,
    budgetMaxINR: 8500000,
    preferredLocation: 'Perungudi, Chennai',
    preferredType: 'APARTMENT',
    interestedPropertyId: 'prop-07',
    interestedPropertyName: 'Casagrand Elysium Township - 2.5BHK Gated Home',
    assignedToId: 'usr-divya-05',
    assignedToName: 'Divya Krishnan',
    score: 20,
    notes: 'Bought resale property in Velachery directly from owner. Closed as lost.',
    createdAt: '2026-08-15T11:00:00Z',
    updatedAt: '2026-09-05T16:00:00Z',
  },
];

// ==========================================
// CLIENTS DATASET (Active Converted Customers)
// ==========================================

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'client-01',
    organizationId: 'org-apex-01',
    name: 'Rajesh Varma',
    phone: '+91 98200 44556',
    email: 'rajesh@varmalogistics.com',
    budgetINR: 52000000,
    preferredLocation: 'ECR, Chennai',
    preferredType: 'PENTHOUSE',
    requirements: 'Sea-facing luxury penthouses and beach villas for vacation rental portfolio.',
    notes: 'VIP Client. Managing 2 luxury assets. Looking for further beachfront plots.',
    totalDealsCount: 2,
    totalDealsValueINR: 88000000,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-09-13T17:30:00Z',
  },
  {
    id: 'client-02',
    organizationId: 'org-apex-01',
    name: 'Dr. Mohan & Sunita Kumar',
    phone: '+91 98400 33221',
    email: 'mohan.sunita@medicare.in',
    budgetINR: 18500000,
    preferredLocation: 'OMR, Chennai',
    preferredType: 'APARTMENT',
    requirements: '3BHK & 4BHK gated apartments near medical institutes.',
    notes: 'Bought unit in Casagrand Elysium in 2025. Interested in upgrading to OMR High-Rise.',
    totalDealsCount: 1,
    totalDealsValueINR: 8400000,
    createdAt: '2026-06-15T11:30:00Z',
    updatedAt: '2026-09-10T14:00:00Z',
  },
  {
    id: 'client-03',
    organizationId: 'org-apex-01',
    name: 'Shankar Mahadevan (Tech Partner)',
    phone: '+91 98840 11009',
    email: 'shankar@cloudscale.io',
    budgetINR: 38000000,
    preferredLocation: 'Whitefield, Bangalore',
    preferredType: 'VILLA',
    requirements: 'Independent villas in gated communities with clubhouses.',
    notes: 'Closed Sobha Windsor villa in Phase 1.',
    totalDealsCount: 1,
    totalDealsValueINR: 38500000,
    createdAt: '2026-07-01T09:00:00Z',
    updatedAt: '2026-09-08T15:20:00Z',
  },
  {
    id: 'client-04',
    organizationId: 'org-apex-01',
    name: 'Lakshmi Narayanan & Co',
    phone: '+91 94440 33445',
    email: 'lnarayanan@auditcorp.in',
    budgetINR: 25000000,
    preferredLocation: 'Coimbatore Race Course',
    preferredType: 'DUPLEX',
    requirements: 'Commercial office spaces and luxury residential suites.',
    notes: 'Regular investor in Coimbatore & Chennai real estate.',
    totalDealsCount: 3,
    totalDealsValueINR: 42000000,
    createdAt: '2026-03-12T14:00:00Z',
    updatedAt: '2026-09-12T11:15:00Z',
  },
];

// ==========================================
// DEALS DATASET & SALES PIPELINE
// ==========================================

export const INITIAL_DEALS: Deal[] = [
  {
    id: 'deal-01',
    organizationId: 'org-apex-01',
    title: 'Emerald Heights 3BHK - Rahul Sharma',
    dealValueINR: 14500000,
    stage: 'NEGOTIATION',
    probability: 80,
    expectedCloseDate: '2026-09-22',
    leadId: 'lead-01',
    leadName: 'Rahul Sharma',
    propertyId: 'prop-01',
    propertyName: 'The Grand Emerald Heights - Luxury 3BHK',
    assignedAgentId: 'usr-karthik-04',
    assignedAgentName: 'Karthik Subramanian',
    notes: 'Price agreed at ₹1.42 Cr all-inclusive. Legal draft under review with client advocate.',
    createdAt: '2026-09-05T12:00:00Z',
    updatedAt: '2026-09-14T11:00:00Z',
  },
  {
    id: 'deal-02',
    organizationId: 'org-apex-01',
    title: 'Sobha Windsor Villa #18 - Dr. Priya',
    dealValueINR: 38500000,
    stage: 'SITE_VISIT',
    probability: 60,
    expectedCloseDate: '2026-10-05',
    leadId: 'lead-02',
    leadName: 'Dr. Priya Raghavan',
    propertyId: 'prop-02',
    propertyName: 'Sobha Windsor Palm Villas - 4BHK Private Villa',
    assignedAgentId: 'usr-ananya-03',
    assignedAgentName: 'Ananya Iyer',
    notes: 'Second in-person site visit scheduled with spouse and architect.',
    createdAt: '2026-09-08T15:00:00Z',
    updatedAt: '2026-09-14T09:45:00Z',
  },
  {
    id: 'deal-03',
    organizationId: 'org-apex-01',
    title: 'Aura Waterfront Penthouse 1801 - Rajesh Varma',
    dealValueINR: 52000000,
    stage: 'CLOSED_WON',
    probability: 100,
    expectedCloseDate: '2026-09-18',
    leadId: 'lead-04',
    leadName: 'Rajesh Varma (Varma Logistics)',
    clientId: 'client-01',
    clientName: 'Rajesh Varma',
    propertyId: 'prop-04',
    propertyName: 'Aura Waterfront Penthouse - 4BHK Sea Facing',
    assignedAgentId: 'usr-vikram-02',
    assignedAgentName: 'Velvet Code',
    notes: 'Token received ₹25 Lakhs. 100% Closed. Commission invoice ₹10.4L generated.',
    createdAt: '2026-08-28T10:00:00Z',
    updatedAt: '2026-09-13T17:30:00Z',
  },
  {
    id: 'deal-04',
    organizationId: 'org-apex-01',
    title: 'Prestige Cyber View 2BHK - Suresh Kumar',
    dealValueINR: 9200000,
    stage: 'QUALIFIED',
    probability: 40,
    expectedCloseDate: '2026-10-15',
    leadId: 'lead-03',
    leadName: 'Suresh Kumar & Meenakshi',
    propertyId: 'prop-03',
    propertyName: 'Prestige Cyber View Residences - 2BHK Smart Home',
    assignedAgentId: 'usr-divya-05',
    assignedAgentName: 'Divya Krishnan',
    notes: 'Evaluating ROI and rental yields against other Hyderabad properties.',
    createdAt: '2026-09-10T11:30:00Z',
    updatedAt: '2026-09-13T16:20:00Z',
  },
  {
    id: 'deal-05',
    organizationId: 'org-apex-01',
    title: 'Brigade BKC Level 9 Commercial - Girish Chandra',
    dealValueINR: 68000000,
    stage: 'QUALIFIED',
    probability: 50,
    expectedCloseDate: '2026-11-01',
    leadId: 'lead-12',
    leadName: 'Girish Chandra & Sons',
    propertyId: 'prop-06',
    propertyName: 'Brigade Signature Commercial Suites - Grade A Office',
    assignedAgentId: 'usr-vikram-02',
    assignedAgentName: 'Velvet Code',
    notes: 'Management board reviewing commercial prospectus and capitalization rate.',
    createdAt: '2026-09-06T16:00:00Z',
    updatedAt: '2026-09-12T17:00:00Z',
  },
  {
    id: 'deal-06',
    organizationId: 'org-apex-01',
    title: 'Emerald Heights 3BHK Unit 1404 - Dr. Anand',
    dealValueINR: 14500000,
    stage: 'DOCUMENTATION',
    probability: 90,
    expectedCloseDate: '2026-09-20',
    leadId: 'lead-10',
    leadName: 'Dr. Anand Ramanathan',
    propertyId: 'prop-01',
    propertyName: 'The Grand Emerald Heights - Luxury 3BHK',
    assignedAgentId: 'usr-karthik-04',
    assignedAgentName: 'Karthik Subramanian',
    notes: 'Booking form signed. Sale agreement stamping in progress.',
    createdAt: '2026-09-03T10:00:00Z',
    updatedAt: '2026-09-14T12:10:00Z',
  },
  {
    id: 'deal-07',
    organizationId: 'org-apex-01',
    title: 'Lodha Park Central Sky Suite - Manish Chawla',
    dealValueINR: 49000000,
    stage: 'SITE_VISIT',
    probability: 50,
    expectedCloseDate: '2026-10-20',
    leadId: 'lead-07',
    leadName: 'Manish Chawla (FinTech Founder)',
    propertyId: 'prop-08',
    propertyName: 'Lodha Park Central Towers - 3BHK Sky Suite',
    assignedAgentId: 'usr-ananya-03',
    assignedAgentName: 'Ananya Iyer',
    notes: 'Attending physical viewing with family this Thursday.',
    createdAt: '2026-09-09T14:00:00Z',
    updatedAt: '2026-09-13T11:40:00Z',
  },
  {
    id: 'deal-08',
    organizationId: 'org-apex-01',
    title: 'Godrej Green Meadows 3BHK - Aditya Deshmukh',
    dealValueINR: 11800000,
    stage: 'NEW_LEAD',
    probability: 25,
    expectedCloseDate: '2026-11-10',
    leadId: 'lead-05',
    leadName: 'Aditya & Neha Deshmukh',
    propertyId: 'prop-05',
    propertyName: 'Godrej Green Meadows - 3BHK Eco Community',
    assignedAgentId: 'usr-karthik-04',
    assignedAgentName: 'Karthik Subramanian',
    notes: 'Initial inquiry via social ad. Requested price list and schedule.',
    createdAt: '2026-09-11T12:00:00Z',
    updatedAt: '2026-09-14T08:15:00Z',
  },
];

// ==========================================
// SITE VISITS DATASET
// ==========================================

export const INITIAL_SITE_VISITS: SiteVisit[] = [
  {
    id: 'visit-01',
    organizationId: 'org-apex-01',
    leadId: 'lead-02',
    leadName: 'Dr. Priya Raghavan',
    customerPhone: '+91 94436 47190',
    propertyId: 'prop-02',
    propertyName: 'Sobha Windsor Palm Villas - 4BHK Private Villa',
    propertyLocation: 'Whitefield, Bangalore',
    assignedAgentId: 'usr-ananya-03',
    assignedAgentName: 'Ananya Iyer',
    visitDate: '2026-09-15',
    timeSlot: '11:00 AM',
    status: 'CONFIRMED',
    notes: 'Client arriving from Indiranagar. Ensure clubhouse keys and master villa unlocked.',
    createdAt: '2026-09-13T10:00:00Z',
  },
  {
    id: 'visit-02',
    organizationId: 'org-apex-01',
    leadId: 'lead-06',
    leadName: 'Kavitha Balasubramanian',
    customerPhone: '+91 94440 88776',
    propertyId: 'prop-10',
    propertyName: 'TVS Emerald Elements - 3BHK Lakeview Residence',
    propertyLocation: 'Kovilambakkam, Chennai',
    assignedAgentId: 'usr-divya-05',
    assignedAgentName: 'Divya Krishnan',
    visitDate: '2026-09-14',
    timeSlot: '04:30 PM',
    status: 'SCHEDULED',
    notes: 'Meet at sales gallery gate #2. Focus on lake promenade and 9th floor views.',
    createdAt: '2026-09-14T10:30:00Z',
  },
  {
    id: 'visit-03',
    organizationId: 'org-apex-01',
    leadId: 'lead-07',
    leadName: 'Manish Chawla',
    customerPhone: '+91 98111 22334',
    propertyId: 'prop-08',
    propertyName: 'Lodha Park Central Towers - 3BHK Sky Suite',
    propertyLocation: 'Worli, Mumbai',
    assignedAgentId: 'usr-ananya-03',
    assignedAgentName: 'Ananya Iyer',
    visitDate: '2026-09-16',
    timeSlot: '03:00 PM',
    status: 'SCHEDULED',
    notes: 'Exclusive private elevator pass requested with security.',
    createdAt: '2026-09-12T14:00:00Z',
  },
  {
    id: 'visit-04',
    organizationId: 'org-apex-01',
    leadId: 'lead-01',
    leadName: 'Rahul Sharma',
    customerPhone: '+91 98401 22334',
    propertyId: 'prop-01',
    propertyName: 'The Grand Emerald Heights - Luxury 3BHK',
    propertyLocation: 'OMR, Chennai',
    assignedAgentId: 'usr-karthik-04',
    assignedAgentName: 'Karthik Subramanian',
    visitDate: '2026-09-12',
    timeSlot: '11:30 AM',
    status: 'COMPLETED',
    checkInAt: '2026-09-12T11:28:00Z',
    checkOutAt: '2026-09-12T12:45:00Z',
    rating: 5,
    feedback:
      'Rahul and his wife loved the 14th-floor balcony and cross ventilation. Moving to price negotiation.',
    photos: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=600&q=80',
    ],
    createdAt: '2026-09-10T09:00:00Z',
  },
  {
    id: 'visit-05',
    organizationId: 'org-apex-01',
    leadId: 'lead-08',
    leadName: 'Senthil Nathan',
    customerPhone: '+91 98422 55667',
    propertyId: 'prop-09',
    propertyName: 'Adroit Altius Haven - 3BHK Duplex Penthouse',
    propertyLocation: 'Race Course, Coimbatore',
    assignedAgentId: 'usr-karthik-04',
    assignedAgentName: 'Karthik Subramanian',
    visitDate: '2026-09-17',
    timeSlot: '10:30 AM',
    status: 'CONFIRMED',
    notes: 'Client driving from Tirupur. Prepared property brochure and elevation floor plan.',
    createdAt: '2026-09-13T11:00:00Z',
  },
];

// ==========================================
// TASKS & FOLLOW-UPS DATASET
// ==========================================

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-01',
    organizationId: 'org-apex-01',
    title: 'Call Rahul Sharma to finalize parking slot allotment',
    description: 'Confirm Tower B basement slot B-14 and B-15 with Emerald Heights builder liaison.',
    priority: 'URGENT',
    status: 'PENDING',
    dueDate: '2026-09-14T15:30:00Z',
    assignedUserId: 'usr-karthik-04',
    assignedUserName: 'Karthik Subramanian',
    leadId: 'lead-01',
    leadName: 'Rahul Sharma',
    dealId: 'deal-01',
    dealTitle: 'Emerald Heights 3BHK - Rahul Sharma',
    propertyId: 'prop-01',
    createdAt: '2026-09-14T09:00:00Z',
  },
  {
    id: 'task-02',
    organizationId: 'org-apex-01',
    title: 'WhatsApp confirmation for Sobha Windsor site visit to Dr. Priya',
    description: 'Send location pin and gate security code for tomorrow morning visit.',
    priority: 'HIGH',
    status: 'PENDING',
    dueDate: '2026-09-14T16:00:00Z',
    assignedUserId: 'usr-ananya-03',
    assignedUserName: 'Ananya Iyer',
    leadId: 'lead-02',
    leadName: 'Dr. Priya Raghavan',
    propertyId: 'prop-02',
    createdAt: '2026-09-14T09:30:00Z',
  },
  {
    id: 'task-03',
    organizationId: 'org-apex-01',
    title: 'Prepare sale deed stamp papers for Rajesh Varma penthouse',
    description: 'Coordinate with sub-registrar office in Neelankarai for registration slot on Friday.',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    dueDate: '2026-09-15T12:00:00Z',
    assignedUserId: 'usr-vikram-02',
    assignedUserName: 'Velvet Code',
    leadId: 'lead-04',
    leadName: 'Rajesh Varma (Varma Logistics)',
    dealId: 'deal-03',
    dealTitle: 'Aura Waterfront Penthouse 1801',
    createdAt: '2026-09-13T14:00:00Z',
  },
  {
    id: 'task-04',
    organizationId: 'org-apex-01',
    title: 'Send Godrej Green Meadows cost sheet to Aditya Deshmukh',
    description: 'Include 3BHK unit 504 price breakdown with GST, car park, and club membership charges.',
    priority: 'MEDIUM',
    status: 'PENDING',
    dueDate: '2026-09-14T17:30:00Z',
    assignedUserId: 'usr-karthik-04',
    assignedUserName: 'Karthik Subramanian',
    leadId: 'lead-05',
    leadName: 'Aditya & Neha Deshmukh',
    propertyId: 'prop-05',
    createdAt: '2026-09-14T11:00:00Z',
  },
  {
    id: 'task-05',
    organizationId: 'org-apex-01',
    title: 'Follow up with Suresh Kumar on Hitec City 2BHK rental yield query',
    description: 'Share rental comps showing current ₹42,000/mo rentals in Mindspace perimeter.',
    priority: 'MEDIUM',
    status: 'PENDING',
    dueDate: '2026-09-14T18:00:00Z',
    assignedUserId: 'usr-divya-05',
    assignedUserName: 'Divya Krishnan',
    leadId: 'lead-03',
    leadName: 'Suresh Kumar',
    propertyId: 'prop-03',
    createdAt: '2026-09-13T16:00:00Z',
  },
  {
    id: 'task-06',
    organizationId: 'org-apex-01',
    title: 'Quarterly VAT & GST reconciliation for commission receivables',
    description: 'Review ₹24.8L gross receipts with internal audit team.',
    priority: 'LOW',
    status: 'COMPLETED',
    dueDate: '2026-09-12T17:00:00Z',
    assignedUserId: 'usr-vikram-02',
    assignedUserName: 'Velvet Code',
    createdAt: '2026-09-08T10:00:00Z',
  },
];

export const INITIAL_FOLLOW_UPS: FollowUpItem[] = [
  {
    id: 'fu-01',
    organizationId: 'org-apex-01',
    leadId: 'lead-01',
    leadName: 'Rahul Sharma',
    customerPhone: '+91 98401 22334',
    propertyName: 'The Grand Emerald Heights (OMR)',
    type: 'CALL',
    scheduledAt: '2026-09-14T15:30:00Z',
    status: 'DUE_TODAY',
    notes: 'Discuss final parking slot confirmation and advocate review remarks.',
  },
  {
    id: 'fu-02',
    organizationId: 'org-apex-01',
    leadId: 'lead-02',
    leadName: 'Dr. Priya Raghavan',
    customerPhone: '+91 94436 47190',
    propertyName: 'Sobha Windsor Palm Villas',
    type: 'WHATSAPP',
    scheduledAt: '2026-09-14T16:00:00Z',
    status: 'DUE_TODAY',
    notes: 'Send WhatsApp reminder for tomorrow 11:00 AM site visit.',
  },
  {
    id: 'fu-03',
    organizationId: 'org-apex-01',
    leadId: 'lead-10',
    leadName: 'Dr. Anand Ramanathan',
    customerPhone: '+91 98403 77112',
    propertyName: 'The Grand Emerald Heights',
    type: 'MEETING',
    scheduledAt: '2026-09-14T18:00:00Z',
    status: 'DUE_TODAY',
    notes: 'Meeting at OMR sales lounge to sign booking application.',
  },
  {
    id: 'fu-04',
    organizationId: 'org-apex-01',
    leadId: 'lead-09',
    leadName: 'Nikhil Agarwal',
    customerPhone: '+91 99300 77665',
    propertyName: 'Purva Clermont Chembur',
    type: 'CALL',
    scheduledAt: '2026-09-13T11:00:00Z',
    status: 'OVERDUE',
    notes: 'Was unable to reach on phone yesterday. Needs re-call.',
  },
  {
    id: 'fu-05',
    organizationId: 'org-apex-01',
    leadId: 'lead-14',
    leadName: 'Rohan Kulkarni',
    customerPhone: '+91 98230 44112',
    propertyName: 'Mahindra Eden Bangalore',
    type: 'SITE_VISIT',
    scheduledAt: '2026-09-16T16:00:00Z',
    status: 'UPCOMING',
    notes: 'Family site visit for Kanakapura forest facing 3BHK unit.',
  },
  {
    id: 'fu-06',
    organizationId: 'org-apex-01',
    leadId: 'lead-08',
    leadName: 'Senthil Nathan',
    customerPhone: '+91 98422 55667',
    propertyName: 'Adroit Altius Haven Coimbatore',
    type: 'SITE_VISIT',
    scheduledAt: '2026-09-17T10:30:00Z',
    status: 'UPCOMING',
    notes: 'Physical walk-through for 3BHK duplex penthouse.',
  },
];

// ==========================================
// WHATSAPP CRM & CONVERSATIONS
// ==========================================

export const INITIAL_WHATSAPP_CONVERSATIONS: WhatsAppConversation[] = [
  {
    id: 'conv-01',
    organizationId: 'org-apex-01',
    customerPhone: '+91 98401 22334',
    customerName: 'Rahul Sharma',
    leadId: 'lead-01',
    leadStatus: 'NEGOTIATION',
    interestedProperty: 'The Grand Emerald Heights (OMR)',
    budget: '₹1.45 Cr',
    lastMessageText: 'Thanks Karthik, I reviewed the legal agreement. Looks good! Can we confirm the second parking slot?',
    lastMessageAt: '2026-09-14T11:42:00Z',
    unreadCount: 1,
    messages: [
      {
        id: 'msg-01-1',
        conversationId: 'conv-01',
        direction: 'INBOUND',
        status: 'READ',
        body: 'Hi, I saw your listing for The Grand Emerald Heights on OMR. Is the 14th-floor 3BHK unit still available?',
        createdAt: '2026-09-04T10:30:00Z',
      },
      {
        id: 'msg-01-2',
        conversationId: 'conv-01',
        direction: 'OUTBOUND',
        status: 'READ',
        body: 'Hello Rahul! Yes, Unit 1402 is available with stunning North-East facing skyline views. I can share the floor plan and schedule a private visit.',
        createdAt: '2026-09-04T10:35:00Z',
      },
      {
        id: 'msg-01-3',
        conversationId: 'conv-01',
        direction: 'OUTBOUND',
        status: 'READ',
        body: 'Hello Rahul, your site visit for The Grand Emerald Heights is confirmed for 12 Sep at 11:30 AM. Our consultant Karthik will assist you.',
        createdAt: '2026-09-10T09:15:00Z',
      },
      {
        id: 'msg-01-4',
        conversationId: 'conv-01',
        direction: 'INBOUND',
        status: 'READ',
        body: 'Had a wonderful visit with my family. The balcony view is phenomenal!',
        createdAt: '2026-09-12T13:10:00Z',
      },
      {
        id: 'msg-01-5',
        conversationId: 'conv-01',
        direction: 'OUTBOUND',
        status: 'READ',
        body: 'Glad you loved it! I have attached the draft agreement with the ₹1.42 Cr negotiated pricing.',
        createdAt: '2026-09-13T15:00:00Z',
      },
      {
        id: 'msg-01-6',
        conversationId: 'conv-01',
        direction: 'INBOUND',
        status: 'DELIVERED',
        body: 'Thanks Karthik, I reviewed the legal agreement. Looks good! Can we confirm the second parking slot?',
        createdAt: '2026-09-14T11:42:00Z',
      },
    ],
  },
  {
    id: 'conv-02',
    organizationId: 'org-apex-01',
    customerPhone: '+91 94436 47190',
    customerName: 'Dr. Priya Raghavan',
    leadId: 'lead-02',
    leadStatus: 'SITE_VISIT',
    interestedProperty: 'Sobha Windsor Palm Villas',
    budget: '₹3.85 Cr',
    lastMessageText: 'See you tomorrow at 11:00 AM at the Sobha Whitefield gate.',
    lastMessageAt: '2026-09-14T10:15:00Z',
    unreadCount: 0,
    messages: [
      {
        id: 'msg-02-1',
        conversationId: 'conv-02',
        direction: 'INBOUND',
        status: 'READ',
        body: 'Hello, I would like to know more about your 4BHK luxury villas in Whitefield Bangalore.',
        createdAt: '2026-09-06T14:15:00Z',
      },
      {
        id: 'msg-02-2',
        conversationId: 'conv-02',
        direction: 'OUTBOUND',
        status: 'READ',
        body: 'Hello Dr. Priya! Thank you for contacting Velvet Code Realty. We have exclusive access to Sobha Windsor Palm Villas with private swimming pools and gardens.',
        createdAt: '2026-09-06T14:20:00Z',
      },
      {
        id: 'msg-02-3',
        conversationId: 'conv-02',
        direction: 'OUTBOUND',
        status: 'READ',
        body: 'Hello Dr. Priya, your site visit for Sobha Windsor Palm Villas is confirmed for 15 Sep at 11:00 AM. Senior consultant Ananya will be there to welcome you.',
        createdAt: '2026-09-13T10:30:00Z',
      },
      {
        id: 'msg-02-4',
        conversationId: 'conv-02',
        direction: 'INBOUND',
        status: 'READ',
        body: 'See you tomorrow at 11:00 AM at the Sobha Whitefield gate.',
        createdAt: '2026-09-14T10:15:00Z',
      },
    ],
  },
  {
    id: 'conv-03',
    organizationId: 'org-apex-01',
    customerPhone: '+91 98200 44556',
    customerName: 'Rajesh Varma',
    leadId: 'lead-04',
    leadStatus: 'WON',
    interestedProperty: 'Aura Waterfront Penthouse (ECR)',
    budget: '₹5.20 Cr',
    lastMessageText: 'Advance transferred via RTGS. Sent UTR receipt on email.',
    lastMessageAt: '2026-09-13T17:30:00Z',
    unreadCount: 0,
    messages: [
      {
        id: 'msg-03-1',
        conversationId: 'conv-03',
        direction: 'OUTBOUND',
        status: 'READ',
        body: 'Congratulations Mr. Varma! We are thrilled to celebrate your acquisition of the Aura Waterfront Penthouse 1801 on ECR.',
        createdAt: '2026-09-13T17:15:00Z',
      },
      {
        id: 'msg-03-2',
        conversationId: 'conv-03',
        direction: 'INBOUND',
        status: 'READ',
        body: 'Advance transferred via RTGS. Sent UTR receipt on email.',
        createdAt: '2026-09-13T17:30:00Z',
      },
    ],
  },
  {
    id: 'conv-04',
    organizationId: 'org-apex-01',
    customerPhone: '+91 98840 99881',
    customerName: 'Suresh Kumar',
    leadId: 'lead-03',
    leadStatus: 'QUALIFIED',
    interestedProperty: 'Prestige Cyber View (Hitec City)',
    budget: '₹92 Lakhs',
    lastMessageText: 'Can you share the expected monthly rental yield analysis for Hitec City?',
    lastMessageAt: '2026-09-13T16:20:00Z',
    unreadCount: 1,
    messages: [
      {
        id: 'msg-04-1',
        conversationId: 'conv-04',
        direction: 'INBOUND',
        status: 'READ',
        body: 'Can you share the expected monthly rental yield analysis for Hitec City?',
        createdAt: '2026-09-13T16:20:00Z',
      },
    ],
  },
];

export const INITIAL_WHATSAPP_TEMPLATES: WhatsAppTemplate[] = [
  {
    id: 'tpl-01',
    organizationId: 'org-apex-01',
    name: 'New Lead Welcome',
    category: 'WELCOME',
    body: 'Hello {{customer_name}}, thank you for your interest in {{property_name}}. Our senior property consultant {{agent_name}} will connect with you shortly with full details.',
    variables: ['customer_name', 'property_name', 'agent_name'],
  },
  {
    id: 'tpl-02',
    organizationId: 'org-apex-01',
    name: 'Site Visit Confirmation',
    category: 'SITE_VISIT',
    body: 'Hello {{customer_name}}, your exclusive site visit for {{property_name}} is confirmed for {{site_visit_date}} at {{site_visit_time}}. Our property expert {{agent_name}} will welcome you at the venue.',
    variables: ['customer_name', 'property_name', 'site_visit_date', 'site_visit_time', 'agent_name'],
  },
  {
    id: 'tpl-03',
    organizationId: 'org-apex-01',
    name: 'Follow-up & Discussion',
    category: 'FOLLOW_UP',
    body: 'Hello {{customer_name}}, just following up regarding your interest in {{property_name}} ({{property_price}}). Would you like to schedule a site visit or have a short phone discussion this week?',
    variables: ['customer_name', 'property_name', 'property_price'],
  },
  {
    id: 'tpl-04',
    organizationId: 'org-apex-01',
    name: 'Deal Celebration & Congratulations',
    category: 'CELEBRATION',
    body: 'Congratulations {{customer_name}}! We are thrilled to celebrate your new home acquisition of {{property_name}}. Thank you for choosing Velvet Code Realty as your trusted partner.',
    variables: ['customer_name', 'property_name'],
  },
  {
    id: 'tpl-05',
    organizationId: 'org-apex-01',
    name: 'Exclusive Price Drop Alert',
    category: 'PRICE_DROP',
    body: 'Hello {{customer_name}}, exclusive update! A premier unit in {{property_name}} is now available at a revised price of {{property_price}}. Let us know if you would like to book an immediate viewing.',
    variables: ['customer_name', 'property_name', 'property_price'],
  },
];

export const INITIAL_AUTOMATIONS: AutomationRule[] = [
  {
    id: 'auto-01',
    organizationId: 'org-apex-01',
    name: 'Instant Welcome WhatsApp on New Lead',
    triggerEvent: 'LEAD_CREATED',
    actionType: 'SEND_WHATSAPP',
    templateId: 'tpl-01',
    templateName: 'New Lead Welcome',
    isActive: true,
    executionCount: 142,
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'auto-02',
    organizationId: 'org-apex-01',
    name: 'Send Instant Confirmation on Site Visit Scheduled',
    triggerEvent: 'VISIT_SCHEDULED',
    actionType: 'SEND_WHATSAPP',
    templateId: 'tpl-02',
    templateName: 'Site Visit Confirmation',
    isActive: true,
    executionCount: 89,
    createdAt: '2026-08-05T11:00:00Z',
  },
  {
    id: 'auto-03',
    organizationId: 'org-apex-01',
    name: 'Send Reminder 1 Day Before Site Visit',
    triggerEvent: 'VISIT_REMINDER_TOMORROW',
    actionType: 'SEND_WHATSAPP',
    templateId: 'tpl-02',
    templateName: 'Site Visit Confirmation',
    isActive: true,
    executionCount: 76,
    createdAt: '2026-08-10T14:00:00Z',
  },
  {
    id: 'auto-04',
    organizationId: 'org-apex-01',
    name: 'Auto-create Follow-up Task for Inactive Leads (3 Days)',
    triggerEvent: 'INACTIVE_3_DAYS',
    actionType: 'CREATE_TASK',
    isActive: true,
    executionCount: 53,
    createdAt: '2026-08-15T09:00:00Z',
  },
  {
    id: 'auto-05',
    organizationId: 'org-apex-01',
    name: 'Send Thank You & Celebration on Deal Won',
    triggerEvent: 'DEAL_WON',
    actionType: 'SEND_WHATSAPP',
    templateId: 'tpl-04',
    templateName: 'Deal Celebration & Congratulations',
    isActive: true,
    executionCount: 18,
    createdAt: '2026-08-20T16:00:00Z',
  },
];

// ==========================================
// DOCUMENTS VAULT
// ==========================================

export const INITIAL_DOCUMENTS: DocumentRecord[] = [
  {
    id: 'doc-01',
    organizationId: 'org-apex-01',
    title: 'Emerald Heights Master Brochure & Floor Plans.pdf',
    category: 'PROPERTY',
    fileUrl: '/docs/emerald-heights-brochure.pdf',
    fileSizeMB: 4.8,
    fileType: 'PDF',
    relatedName: 'The Grand Emerald Heights (OMR)',
    createdAt: '2026-08-12T10:00:00Z',
  },
  {
    id: 'doc-02',
    organizationId: 'org-apex-01',
    title: 'Sobha Windsor Villa Elevation & Layout Specs.pdf',
    category: 'PROPERTY',
    fileUrl: '/docs/sobha-windsor-specs.pdf',
    fileSizeMB: 6.2,
    fileType: 'PDF',
    relatedName: 'Sobha Windsor Palm Villas',
    createdAt: '2026-08-16T14:00:00Z',
  },
  {
    id: 'doc-03',
    organizationId: 'org-apex-01',
    title: 'Draft Sale Agreement - Aura Waterfront Penthouse 1801.pdf',
    category: 'LEGAL',
    fileUrl: '/docs/draft-sale-agreement-aura.pdf',
    fileSizeMB: 2.1,
    fileType: 'PDF',
    relatedName: 'Rajesh Varma (Varma Logistics)',
    createdAt: '2026-09-13T16:00:00Z',
  },
  {
    id: 'doc-04',
    organizationId: 'org-apex-01',
    title: 'Client KYC & PAN Verified - Dr Priya Raghavan.pdf',
    category: 'CLIENT_KYC',
    fileUrl: '/docs/kyc-priya-raghavan.pdf',
    fileSizeMB: 1.4,
    fileType: 'PDF',
    relatedName: 'Dr. Priya Raghavan',
    createdAt: '2026-09-07T11:00:00Z',
  },
];

// ==========================================
// NOTIFICATIONS & AUDIT LOGS
// ==========================================

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-01',
    organizationId: 'org-apex-01',
    title: 'New WhatsApp Inquiry',
    message: 'Rahul Sharma responded: "Can we confirm the second parking slot?"',
    type: 'WHATSAPP',
    isRead: false,
    link: '/app/whatsapp',
    createdAt: '2026-09-14T11:42:00Z',
  },
  {
    id: 'notif-02',
    organizationId: 'org-apex-01',
    title: 'Upcoming Site Visit in 2 Hours',
    message: 'Kavitha Balasubramanian at TVS Emerald Elements (04:30 PM).',
    type: 'VISIT',
    isRead: false,
    link: '/app/site-visits',
    createdAt: '2026-09-14T10:30:00Z',
  },
  {
    id: 'notif-03',
    organizationId: 'org-apex-01',
    title: 'Deal Won Milestone! 🎉',
    message: 'Aura Waterfront Penthouse deal won for ₹5.20 Cr by Velvet Code.',
    type: 'LEAD',
    isRead: true,
    link: '/app/deals',
    createdAt: '2026-09-13T17:30:00Z',
  },
  {
    id: 'notif-04',
    organizationId: 'org-apex-01',
    title: 'High Conversion Lead Detected by Realty AI',
    message: 'Dr. Anand Ramanathan scored 94% conversion probability.',
    type: 'AI',
    isRead: true,
    link: '/app/leads',
    createdAt: '2026-09-14T09:00:00Z',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLogItem[] = [
  {
    id: 'act-01',
    organizationId: 'org-apex-01',
    userName: 'Karthik Subramanian',
    action: 'UPDATED_LEAD',
    entityType: 'Lead',
    entityId: 'lead-01',
    entityName: 'Rahul Sharma',
    description: 'Updated lead status to Negotiation and noted ₹1.42 Cr target price.',
    createdAt: '2026-09-14T11:00:00Z',
  },
  {
    id: 'act-02',
    organizationId: 'org-apex-01',
    userName: 'Divya Krishnan',
    action: 'SCHEDULED_VISIT',
    entityType: 'SiteVisit',
    entityId: 'visit-02',
    entityName: 'TVS Emerald Elements',
    description: 'Scheduled site visit for Kavitha Balasubramanian on 14 Sep at 04:30 PM.',
    createdAt: '2026-09-14T10:30:00Z',
  },
  {
    id: 'act-03',
    organizationId: 'org-apex-01',
    userName: 'Velvet Code',
    action: 'CLOSED_DEAL',
    entityType: 'Deal',
    entityId: 'deal-03',
    entityName: 'Aura Waterfront Penthouse',
    description: 'Marked deal as Closed Won for ₹5.20 Cr with token advance confirmation.',
    createdAt: '2026-09-13T17:30:00Z',
  },
  {
    id: 'act-04',
    organizationId: 'org-apex-01',
    userName: 'Ananya Iyer',
    action: 'CONFIRMED_VISIT',
    entityType: 'SiteVisit',
    entityId: 'visit-01',
    entityName: 'Sobha Windsor Palm Villas',
    description: 'Confirmed physical visit for Dr. Priya Raghavan on 15 Sep at 11:00 AM.',
    createdAt: '2026-09-13T10:00:00Z',
  },
  {
    id: 'act-05',
    organizationId: 'org-apex-01',
    userName: 'Karthik Subramanian',
    action: 'COMPLETED_VISIT',
    entityType: 'SiteVisit',
    entityId: 'visit-04',
    entityName: 'The Grand Emerald Heights',
    description: 'Logged 5-star site visit completion and uploaded client feedback.',
    createdAt: '2026-09-12T12:45:00Z',
  },
];

// ==========================================
// INVOICES & BILLING HISTORY
// ==========================================

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-01',
    organizationId: 'org-apex-01',
    invoiceNumber: 'VC-INV-2026-0901',
    amountINR: 1499,
    taxINR: 270,
    totalINR: 1769,
    status: 'paid',
    paymentMethod: 'UPI / Razorpay',
    billingPeriodStart: '2026-09-01T00:00:00Z',
    billingPeriodEnd: '2026-10-01T00:00:00Z',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'inv-02',
    organizationId: 'org-apex-01',
    invoiceNumber: 'VC-INV-2026-0801',
    amountINR: 1499,
    taxINR: 270,
    totalINR: 1769,
    status: 'paid',
    paymentMethod: 'UPI / Razorpay',
    billingPeriodStart: '2026-08-01T00:00:00Z',
    billingPeriodEnd: '2026-09-01T00:00:00Z',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-03',
    organizationId: 'org-apex-01',
    invoiceNumber: 'VC-INV-2026-0701',
    amountINR: 1499,
    taxINR: 270,
    totalINR: 1769,
    status: 'paid',
    paymentMethod: 'UPI / Razorpay',
    billingPeriodStart: '2026-07-01T00:00:00Z',
    billingPeriodEnd: '2026-08-01T00:00:00Z',
    createdAt: '2026-07-01T00:00:00Z',
  },
];

// ==========================================
// SAAS ADMIN MASTER OVERVIEW METRICS
// ==========================================

export const SAAS_ADMIN_STATS: SaaSAdminOverview = {
  totalOrganizations: 1248,
  activeSubscriptions: 864,
  monthlyRecurringRevenueINR: 1240000, // ₹12.4 Lakhs MRR
  newCustomersThisMonth: 84,
  churnRatePercent: 3.2,
  totalActiveUsers: 3420,
  totalLeadsManaged: 84200,
  totalPropertiesListed: 12600,
  aiRequestsProcessed: 184500,
  whatsappMessagesSent: 432000,
};
